name: Create Release

on:
  push:
    tags:
      - 'v*'
  
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: v0.0.1 # Optional fallback tag to use when no tag can be found

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "todo"
            body: |
                **Full Changelog**: https://github.com/schramm42/todo/compare/${{ steps.previoustag.outputs.tag }}...${{ github.ref }}
            draft: false
            prerelease: false
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: swift build -v -c release -Xswiftc -cross-module-optimization

      - uses: actions/upload-artifact@v3
        with:
          name: todo
          path: .build/release/todo
