name: Create Release

on:
  push:
    tags:
      - 'v*'
  
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: swift build -v -c release -Xswiftc -cross-module-optimization

      - uses: actions/upload-artifact@v3
        with:
          name: todo
          path: .build/release/todo

      - name: Get tags
        id: tags
        uses: schramm42/github-action-get-tags@v1
          
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "todo"
            body: |
                **Full Changelog**: https://github.com/schramm42/todo/compare/${{ steps.tags.outputs.previousTag }}...${{ steps.tags.outputs.currentTag }}
            draft: false
            prerelease: false
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
