name: Create Release

on:
  push:
    tags:
      - 'v*'
  
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.set-version.outputs.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Version
        id: set-version
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo "VERSION=${VERSION}"
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # [ubuntu-latest, windows-latest, macos-latest] 
        # include:
        #   - os: windows-latest
        #     setup: bla
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get tags
        id: tags
        uses: schramm42/github-action-get-tags@v1

      - name: Build
        # if: ${{ matrix.setup }}
        # uses: compnerd/gha-setup-swift@main
        # with:
        #   branch: swift-5.8.1-release
        #   tag: 5.8.1-RELEASE
        uses: swift-actions/setup-swift@v1
      - run: swift build -v -c release -Xswiftc -cross-module-optimization

      - uses: actions/upload-artifact@v3
        with:
          name: todo-${{ matrix.os }}-${{ needs.prepare.outputs.VERSION }}.zip
          path: .build/release/todo


          
      # - name: Create Release
      #   id: create_release
      #   uses: ncipollo/release-action@v1
      #   with:
      #       artifacts: .build/release/todo
      #       body: |
      #           **Full Changelog**: https://github.com/schramm42/todo/compare/${{ steps.tags.outputs.previousTag }}...${{ steps.tags.outputs.currentTag }}
      #       draft: false
      #       prerelease: false
      #   env: 
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
